version: '3.8'

services:

  spark-master:
    image: 'apache/spark:3.1.2'
    ports:
      - '8080:8080'
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_LOCAL_DIRS=/tmp/spark-local-dirs

    spark-worker:
      image: 'apache/spark:3.1.2'
      depends_on:
        - spark-master
      environment:
        - SPARK_MASTER_URL=spark://spark-master:7077

  hadoop-namenode:
    image: 'actionml/hadoop'
    ports:
      - '9870:9870'
      - '50070:50070'
    environment:
      - HADOOP_NAMENODE_HOST=hadoop-namenode

    hadoop-datanode:
      image: 'actionml/hadoop'
      depends_on:
        - hadoop-namenode

  postgres:
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

  api:
    image: 'python:3.9-slim'
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    depends_on:
      - spark-master
      - postgres

volumes:
  spark-local-dirs: