version: '3.8'

services:

  spark-master:
    image: 'bitnami/spark:3.1.2-hadoop-3.2.1'
    ports:
      - '8080:8080'
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_LOCAL_DIRS=/tmp/spark-local-dirs

  spark-worker:
    image: 'bitnami/spark:3.1.2-hadoop-3.2.1'
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077

  hadoop-namenode:
    image: 'bitnami/hadoop:3.2.1'
    ports:
      - '9870:9870'
      - '50070:50070'
    environment:
      - HADOOP_NAMENODE_HOST=hadoop-namenode

  hadoop-datanode:
    image: 'bitnami/hadoop:3.2.1'
    depends_on:
      - hadoop-namenode

  postgres:
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

  api:
    image: 'python:3.9-slim'
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    depends_on:
      - spark-master
      - postgres
    command: ['python', 'app.py']

volumes:
  spark-local-dirs: